# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'repoconfig.ui'
#
# Created: Tue Aug 23 18:38:46 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_repoConfig(object):
    def setupUi(self, repoConfig):
        repoConfig.setObjectName(_fromUtf8("repoConfig"))
        repoConfig.resize(420, 260)
        repoConfig.setMinimumSize(QtCore.QSize(420, 260))
        repoConfig.setMaximumSize(QtCore.QSize(420, 260))
        self.verticalLayout = QtGui.QVBoxLayout(repoConfig)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(repoConfig)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabServer = QtGui.QWidget()
        self.tabServer.setObjectName(_fromUtf8("tabServer"))
        self.formLayout = QtGui.QFormLayout(self.tabServer)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelName = QtGui.QLabel(self.tabServer)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelName)
        self.lineEditName = QtGui.QLineEdit(self.tabServer)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditName)
        self.labelHost = QtGui.QLabel(self.tabServer)
        self.labelHost.setObjectName(_fromUtf8("labelHost"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHost)
        self.lineEditHost = QtGui.QLineEdit(self.tabServer)
        self.lineEditHost.setObjectName(_fromUtf8("lineEditHost"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditHost)
        self.labelPort = QtGui.QLabel(self.tabServer)
        self.labelPort.setObjectName(_fromUtf8("labelPort"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelPort)
        self.spinBoxPort = QtGui.QSpinBox(self.tabServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxPort.sizePolicy().hasHeightForWidth())
        self.spinBoxPort.setSizePolicy(sizePolicy)
        self.spinBoxPort.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxPort.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxPort.setMinimum(1)
        self.spinBoxPort.setMaximum(65535)
        self.spinBoxPort.setProperty(_fromUtf8("value"), 1356)
        self.spinBoxPort.setObjectName(_fromUtf8("spinBoxPort"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxPort)
        self.checkBoxEnabled = QtGui.QCheckBox(self.tabServer)
        self.checkBoxEnabled.setObjectName(_fromUtf8("checkBoxEnabled"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBoxEnabled)
        self.lineEditRemotePath = QtGui.QLineEdit(self.tabServer)
        self.lineEditRemotePath.setObjectName(_fromUtf8("lineEditRemotePath"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditRemotePath)
        self.labelRemotePath = QtGui.QLabel(self.tabServer)
        self.labelRemotePath.setObjectName(_fromUtf8("labelRemotePath"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelRemotePath)
        self.tabWidget.addTab(self.tabServer, _fromUtf8(""))
        self.tabAuth = QtGui.QWidget()
        self.tabAuth.setObjectName(_fromUtf8("tabAuth"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabAuth)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelAuthType = QtGui.QLabel(self.tabAuth)
        self.labelAuthType.setObjectName(_fromUtf8("labelAuthType"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelAuthType)
        self.comboBoxAuthType = QtGui.QComboBox(self.tabAuth)
        self.comboBoxAuthType.setObjectName(_fromUtf8("comboBoxAuthType"))
        self.comboBoxAuthType.addItem(_fromUtf8(""))
        self.comboBoxAuthType.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxAuthType)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem)
        self.labelUsername = QtGui.QLabel(self.tabAuth)
        self.labelUsername.setObjectName(_fromUtf8("labelUsername"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelUsername)
        self.lineEditUsername = QtGui.QLineEdit(self.tabAuth)
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditUsername)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(self.tabAuth)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.rsapage = QtGui.QWidget()
        self.rsapage.setObjectName(_fromUtf8("rsapage"))
        self.gridLayout = QtGui.QGridLayout(self.rsapage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelRSA = QtGui.QLabel(self.rsapage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRSA.sizePolicy().hasHeightForWidth())
        self.labelRSA.setSizePolicy(sizePolicy)
        self.labelRSA.setObjectName(_fromUtf8("labelRSA"))
        self.gridLayout.addWidget(self.labelRSA, 0, 0, 1, 1)
        self.lineEditRSA = QtGui.QLineEdit(self.rsapage)
        self.lineEditRSA.setObjectName(_fromUtf8("lineEditRSA"))
        self.gridLayout.addWidget(self.lineEditRSA, 1, 0, 1, 1)
        self.toolButtonFileRSA = QtGui.QToolButton(self.rsapage)
        self.toolButtonFileRSA.setObjectName(_fromUtf8("toolButtonFileRSA"))
        self.gridLayout.addWidget(self.toolButtonFileRSA, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.rsapage)
        self.passpage = QtGui.QWidget()
        self.passpage.setObjectName(_fromUtf8("passpage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.passpage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelPassword = QtGui.QLabel(self.passpage)
        self.labelPassword.setObjectName(_fromUtf8("labelPassword"))
        self.gridLayout_2.addWidget(self.labelPassword, 0, 0, 1, 1)
        self.lineEditPassword = QtGui.QLineEdit(self.passpage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.gridLayout_2.addWidget(self.lineEditPassword, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(78, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.passpage)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.passpage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tabAuth, _fromUtf8(""))
        self.tabStorage = QtGui.QWidget()
        self.tabStorage.setObjectName(_fromUtf8("tabStorage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabStorage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelLocalPath = QtGui.QLabel(self.tabStorage)
        self.labelLocalPath.setObjectName(_fromUtf8("labelLocalPath"))
        self.horizontalLayout.addWidget(self.labelLocalPath)
        self.lineEditLocalPath = QtGui.QLineEdit(self.tabStorage)
        self.lineEditLocalPath.setObjectName(_fromUtf8("lineEditLocalPath"))
        self.horizontalLayout.addWidget(self.lineEditLocalPath)
        self.toolButtonLocalPath = QtGui.QToolButton(self.tabStorage)
        self.toolButtonLocalPath.setObjectName(_fromUtf8("toolButtonLocalPath"))
        self.horizontalLayout.addWidget(self.toolButtonLocalPath)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.tabStorage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.labelInternal = QtGui.QLabel(self.tabStorage)
        self.labelInternal.setObjectName(_fromUtf8("labelInternal"))
        self.verticalLayout_3.addWidget(self.labelInternal)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelHashes = QtGui.QLabel(self.tabStorage)
        self.labelHashes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHashes.setObjectName(_fromUtf8("labelHashes"))
        self.gridLayout_3.addWidget(self.labelHashes, 0, 0, 1, 1)
        self.lineEditHashes = QtGui.QLineEdit(self.tabStorage)
        self.lineEditHashes.setObjectName(_fromUtf8("lineEditHashes"))
        self.gridLayout_3.addWidget(self.lineEditHashes, 0, 1, 1, 1)
        self.toolButtonHashes = QtGui.QToolButton(self.tabStorage)
        self.toolButtonHashes.setObjectName(_fromUtf8("toolButtonHashes"))
        self.gridLayout_3.addWidget(self.toolButtonHashes, 0, 2, 1, 1)
        self.toolButtonDB = QtGui.QToolButton(self.tabStorage)
        self.toolButtonDB.setObjectName(_fromUtf8("toolButtonDB"))
        self.gridLayout_3.addWidget(self.toolButtonDB, 1, 2, 1, 1)
        self.lineEditDB = QtGui.QLineEdit(self.tabStorage)
        self.lineEditDB.setObjectName(_fromUtf8("lineEditDB"))
        self.gridLayout_3.addWidget(self.lineEditDB, 1, 1, 1, 1)
        self.labelDB = QtGui.QLabel(self.tabStorage)
        self.labelDB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDB.setObjectName(_fromUtf8("labelDB"))
        self.gridLayout_3.addWidget(self.labelDB, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tabStorage, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(repoConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(repoConfig)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), repoConfig.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), repoConfig.reject)
        QtCore.QObject.connect(self.comboBoxAuthType, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(repoConfig)

    def retranslateUi(self, repoConfig):
        repoConfig.setWindowTitle(QtGui.QApplication.translate("repoConfig", "Repository configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.labelName.setText(QtGui.QApplication.translate("repoConfig", "Repository name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHost.setText(QtGui.QApplication.translate("repoConfig", "Hostname or IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("repoConfig", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEnabled.setText(QtGui.QApplication.translate("repoConfig", "Enable repository (keep in sync)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRemotePath.setText(QtGui.QApplication.translate("repoConfig", "Remote folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServer), QtGui.QApplication.translate("repoConfig", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAuthType.setText(QtGui.QApplication.translate("repoConfig", "Type of authentication:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAuthType.setItemText(0, QtGui.QApplication.translate("repoConfig", "RSA public key", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAuthType.setItemText(1, QtGui.QApplication.translate("repoConfig", "Plain password", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUsername.setText(QtGui.QApplication.translate("repoConfig", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRSA.setText(QtGui.QApplication.translate("repoConfig", "Private RSA key file:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFileRSA.setText(QtGui.QApplication.translate("repoConfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPassword.setText(QtGui.QApplication.translate("repoConfig", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("repoConfig", "Mask password", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAuth), QtGui.QApplication.translate("repoConfig", "Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocalPath.setText(QtGui.QApplication.translate("repoConfig", "Local path:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonLocalPath.setText(QtGui.QApplication.translate("repoConfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInternal.setText(QtGui.QApplication.translate("repoConfig", "Internal configuration:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHashes.setText(QtGui.QApplication.translate("repoConfig", "Hash directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonHashes.setText(QtGui.QApplication.translate("repoConfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonDB.setText(QtGui.QApplication.translate("repoConfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDB.setText(QtGui.QApplication.translate("repoConfig", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStorage), QtGui.QApplication.translate("repoConfig", "Local storage", None, QtGui.QApplication.UnicodeUTF8))

